// Permission resource/action/scope constants
export const PERMISSION_DEALERSHIP_CREATE_OWN = "dealership:create:own";
export const PERMISSION_DEALERSHIP_CREATE_ANY = "dealership:create:any";
export const PERMISSION_DEALERSHIP_READ_OWN = "dealership:read:own";
export const PERMISSION_DEALERSHIP_READ_ANY = "dealership:read:any";
export const PERMISSION_DEALERSHIP_UPDATE_OWN = "dealership:update:own";
export const PERMISSION_DEALERSHIP_UPDATE_ANY = "dealership:update:any";
export const PERMISSION_DEALERSHIP_DELETE_OWN = "dealership:delete:own";
export const PERMISSION_DEALERSHIP_DELETE_ANY = "dealership:delete:any";

export const PERMISSION_OUTLET_CREATE_OWN = "outlet:create:own";
export const PERMISSION_OUTLET_CREATE_ANY = "outlet:create:any";
export const PERMISSION_OUTLET_READ_OWN = "outlet:read:own";
export const PERMISSION_OUTLET_READ_ANY = "outlet:read:any";
export const PERMISSION_OUTLET_UPDATE_OWN = "outlet:update:own";
export const PERMISSION_OUTLET_UPDATE_ANY = "outlet:update:any";
export const PERMISSION_OUTLET_DELETE_OWN = "outlet:delete:own";
export const PERMISSION_OUTLET_DELETE_ANY = "outlet:delete:any";

export const PERMISSION_USER_CREATE_OWN = "user:create:own";
export const PERMISSION_USER_CREATE_ANY = "user:create:any";
export const PERMISSION_USER_READ_OWN = "user:read:own";
export const PERMISSION_USER_READ_ANY = "user:read:any";
export const PERMISSION_USER_UPDATE_OWN = "user:update:own";
export const PERMISSION_USER_UPDATE_ANY = "user:update:any";
export const PERMISSION_USER_DELETE_OWN = "user:delete:own";
export const PERMISSION_USER_DELETE_ANY = "user:delete:any";

export const PERMISSION_VEHICLE_CREATE_OWN = "vehicle:create:own";
export const PERMISSION_VEHICLE_CREATE_ANY = "vehicle:create:any";
export const PERMISSION_VEHICLE_READ_OWN = "vehicle:read:own";
export const PERMISSION_VEHICLE_READ_ANY = "vehicle:read:any";
export const PERMISSION_VEHICLE_UPDATE_OWN = "vehicle:update:own";
export const PERMISSION_VEHICLE_UPDATE_ANY = "vehicle:update:any";
export const PERMISSION_VEHICLE_DELETE_OWN = "vehicle:delete:own";
export const PERMISSION_VEHICLE_DELETE_ANY = "vehicle:delete:any";

export const PERMISSION_CUSTOMER_CREATE_OWN = "customer:create:own";
export const PERMISSION_CUSTOMER_CREATE_ANY = "customer:create:any";
export const PERMISSION_CUSTOMER_READ_OWN = "customer:read:own";
export const PERMISSION_CUSTOMER_READ_ANY = "customer:read:any";
export const PERMISSION_CUSTOMER_UPDATE_OWN = "customer:update:own";
export const PERMISSION_CUSTOMER_UPDATE_ANY = "customer:update:any";
export const PERMISSION_CUSTOMER_DELETE_OWN = "customer:delete:own";
export const PERMISSION_CUSTOMER_DELETE_ANY = "customer:delete:any";

export const PERMISSION_SALE_CREATE_OWN = "sale:create:own";
export const PERMISSION_SALE_CREATE_ANY = "sale:create:any";
export const PERMISSION_SALE_READ_OWN = "sale:read:own";
export const PERMISSION_SALE_READ_ANY = "sale:read:any";
export const PERMISSION_SALE_UPDATE_OWN = "sale:update:own";
export const PERMISSION_SALE_UPDATE_ANY = "sale:update:any";
export const PERMISSION_SALE_DELETE_OWN = "sale:delete:own";
export const PERMISSION_SALE_DELETE_ANY = "sale:delete:any";

export const PERMISSION_PAYMENT_CREATE_OWN = "payment:create:own";
export const PERMISSION_PAYMENT_CREATE_ANY = "payment:create:any";
export const PERMISSION_PAYMENT_READ_OWN = "payment:read:own";
export const PERMISSION_PAYMENT_READ_ANY = "payment:read:any";
export const PERMISSION_PAYMENT_UPDATE_OWN = "payment:update:own";
export const PERMISSION_PAYMENT_UPDATE_ANY = "payment:update:any";
export const PERMISSION_PAYMENT_DELETE_OWN = "payment:delete:own";
export const PERMISSION_PAYMENT_DELETE_ANY = "payment:delete:any";

export const PERMISSION_APPROVAL_CREATE_OWN = "approval:create:own";
export const PERMISSION_APPROVAL_CREATE_ANY = "approval:create:any";
export const PERMISSION_APPROVAL_READ_OWN = "approval:read:own";
export const PERMISSION_APPROVAL_READ_ANY = "approval:read:any";
export const PERMISSION_APPROVAL_UPDATE_OWN = "approval:update:own";
export const PERMISSION_APPROVAL_UPDATE_ANY = "approval:update:any";
export const PERMISSION_APPROVAL_DELETE_OWN = "approval:delete:own";
export const PERMISSION_APPROVAL_DELETE_ANY = "approval:delete:any";

export const PERMISSION_DELIVERYCHALLAN_CREATE_OWN =
  "deliveryChallan:create:own";
export const PERMISSION_DELIVERYCHALLAN_CREATE_ANY =
  "deliveryChallan:create:any";
export const PERMISSION_DELIVERYCHALLAN_READ_OWN = "deliveryChallan:read:own";
export const PERMISSION_DELIVERYCHALLAN_READ_ANY = "deliveryChallan:read:any";
export const PERMISSION_DELIVERYCHALLAN_UPDATE_OWN =
  "deliveryChallan:update:own";
export const PERMISSION_DELIVERYCHALLAN_UPDATE_ANY =
  "deliveryChallan:update:any";
export const PERMISSION_DELIVERYCHALLAN_DELETE_OWN =
  "deliveryChallan:delete:own";
export const PERMISSION_DELIVERYCHALLAN_DELETE_ANY =
  "deliveryChallan:delete:any";

export const PERMISSION_DOCUMENT_CREATE_OWN = "document:create:own";
export const PERMISSION_DOCUMENT_CREATE_ANY = "document:create:any";
export const PERMISSION_DOCUMENT_READ_OWN = "document:read:own";
export const PERMISSION_DOCUMENT_READ_ANY = "document:read:any";
export const PERMISSION_DOCUMENT_UPDATE_OWN = "document:update:own";
export const PERMISSION_DOCUMENT_UPDATE_ANY = "document:update:any";
export const PERMISSION_DOCUMENT_DELETE_OWN = "document:delete:own";
export const PERMISSION_DOCUMENT_DELETE_ANY = "document:delete:any";

export const PERMISSION_KYCDOCUMENT_CREATE_OWN = "kycDocument:create:own";
export const PERMISSION_KYCDOCUMENT_CREATE_ANY = "kycDocument:create:any";
export const PERMISSION_KYCDOCUMENT_READ_OWN = "kycDocument:read:own";
export const PERMISSION_KYCDOCUMENT_READ_ANY = "kycDocument:read:any";
export const PERMISSION_KYCDOCUMENT_UPDATE_OWN = "kycDocument:update:own";
export const PERMISSION_KYCDOCUMENT_UPDATE_ANY = "kycDocument:update:any";
export const PERMISSION_KYCDOCUMENT_DELETE_OWN = "kycDocument:delete:own";
export const PERMISSION_KYCDOCUMENT_DELETE_ANY = "kycDocument:delete:any";

export const PERMISSION_ROLE_CREATE_OWN = "role:create:own";
export const PERMISSION_ROLE_CREATE_ANY = "role:create:any";
export const PERMISSION_ROLE_READ_OWN = "role:read:own";
export const PERMISSION_ROLE_READ_ANY = "role:read:any";
export const PERMISSION_ROLE_UPDATE_OWN = "role:update:own";
export const PERMISSION_ROLE_UPDATE_ANY = "role:update:any";
export const PERMISSION_ROLE_DELETE_OWN = "role:delete:own";
export const PERMISSION_ROLE_DELETE_ANY = "role:delete:any";

// Grouped permissions for easy access
export const PERMISSIONS = {
  DEALERSHIP: {
    CREATE_OWN: PERMISSION_DEALERSHIP_CREATE_OWN,
    CREATE_ANY: PERMISSION_DEALERSHIP_CREATE_ANY,
    READ_OWN: PERMISSION_DEALERSHIP_READ_OWN,
    READ_ANY: PERMISSION_DEALERSHIP_READ_ANY,
    UPDATE_OWN: PERMISSION_DEALERSHIP_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_DEALERSHIP_UPDATE_ANY,
    DELETE_OWN: PERMISSION_DEALERSHIP_DELETE_OWN,
    DELETE_ANY: PERMISSION_DEALERSHIP_DELETE_ANY,
  },
  OUTLET: {
    CREATE_OWN: PERMISSION_OUTLET_CREATE_OWN,
    CREATE_ANY: PERMISSION_OUTLET_CREATE_ANY,
    READ_OWN: PERMISSION_OUTLET_READ_OWN,
    READ_ANY: PERMISSION_OUTLET_READ_ANY,
    UPDATE_OWN: PERMISSION_OUTLET_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_OUTLET_UPDATE_ANY,
    DELETE_OWN: PERMISSION_OUTLET_DELETE_OWN,
    DELETE_ANY: PERMISSION_OUTLET_DELETE_ANY,
  },
  USER: {
    CREATE_OWN: PERMISSION_USER_CREATE_OWN,
    CREATE_ANY: PERMISSION_USER_CREATE_ANY,
    READ_OWN: PERMISSION_USER_READ_OWN,
    READ_ANY: PERMISSION_USER_READ_ANY,
    UPDATE_OWN: PERMISSION_USER_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_USER_UPDATE_ANY,
    DELETE_OWN: PERMISSION_USER_DELETE_OWN,
    DELETE_ANY: PERMISSION_USER_DELETE_ANY,
  },
  VEHICLE: {
    CREATE_OWN: PERMISSION_VEHICLE_CREATE_OWN,
    CREATE_ANY: PERMISSION_VEHICLE_CREATE_ANY,
    READ_OWN: PERMISSION_VEHICLE_READ_OWN,
    READ_ANY: PERMISSION_VEHICLE_READ_ANY,
    UPDATE_OWN: PERMISSION_VEHICLE_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_VEHICLE_UPDATE_ANY,
    DELETE_OWN: PERMISSION_VEHICLE_DELETE_OWN,
    DELETE_ANY: PERMISSION_VEHICLE_DELETE_ANY,
  },
  CUSTOMER: {
    CREATE_OWN: PERMISSION_CUSTOMER_CREATE_OWN,
    CREATE_ANY: PERMISSION_CUSTOMER_CREATE_ANY,
    READ_OWN: PERMISSION_CUSTOMER_READ_OWN,
    READ_ANY: PERMISSION_CUSTOMER_READ_ANY,
    UPDATE_OWN: PERMISSION_CUSTOMER_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_CUSTOMER_UPDATE_ANY,
    DELETE_OWN: PERMISSION_CUSTOMER_DELETE_OWN,
    DELETE_ANY: PERMISSION_CUSTOMER_DELETE_ANY,
  },
  SALE: {
    CREATE_OWN: PERMISSION_SALE_CREATE_OWN,
    CREATE_ANY: PERMISSION_SALE_CREATE_ANY,
    READ_OWN: PERMISSION_SALE_READ_OWN,
    READ_ANY: PERMISSION_SALE_READ_ANY,
    UPDATE_OWN: PERMISSION_SALE_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_SALE_UPDATE_ANY,
    DELETE_OWN: PERMISSION_SALE_DELETE_OWN,
    DELETE_ANY: PERMISSION_SALE_DELETE_ANY,
  },
  PAYMENT: {
    CREATE_OWN: PERMISSION_PAYMENT_CREATE_OWN,
    CREATE_ANY: PERMISSION_PAYMENT_CREATE_ANY,
    READ_OWN: PERMISSION_PAYMENT_READ_OWN,
    READ_ANY: PERMISSION_PAYMENT_READ_ANY,
    UPDATE_OWN: PERMISSION_PAYMENT_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_PAYMENT_UPDATE_ANY,
    DELETE_OWN: PERMISSION_PAYMENT_DELETE_OWN,
    DELETE_ANY: PERMISSION_PAYMENT_DELETE_ANY,
  },
  APPROVAL: {
    CREATE_OWN: PERMISSION_APPROVAL_CREATE_OWN,
    CREATE_ANY: PERMISSION_APPROVAL_CREATE_ANY,
    READ_OWN: PERMISSION_APPROVAL_READ_OWN,
    READ_ANY: PERMISSION_APPROVAL_READ_ANY,
    UPDATE_OWN: PERMISSION_APPROVAL_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_APPROVAL_UPDATE_ANY,
    DELETE_OWN: PERMISSION_APPROVAL_DELETE_OWN,
    DELETE_ANY: PERMISSION_APPROVAL_DELETE_ANY,
  },
  DELIVERYCHALLAN: {
    CREATE_OWN: PERMISSION_DELIVERYCHALLAN_CREATE_OWN,
    CREATE_ANY: PERMISSION_DELIVERYCHALLAN_CREATE_ANY,
    READ_OWN: PERMISSION_DELIVERYCHALLAN_READ_OWN,
    READ_ANY: PERMISSION_DELIVERYCHALLAN_READ_ANY,
    UPDATE_OWN: PERMISSION_DELIVERYCHALLAN_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_DELIVERYCHALLAN_UPDATE_ANY,
    DELETE_OWN: PERMISSION_DELIVERYCHALLAN_DELETE_OWN,
    DELETE_ANY: PERMISSION_DELIVERYCHALLAN_DELETE_ANY,
  },
  DOCUMENT: {
    CREATE_OWN: PERMISSION_DOCUMENT_CREATE_OWN,
    CREATE_ANY: PERMISSION_DOCUMENT_CREATE_ANY,
    READ_OWN: PERMISSION_DOCUMENT_READ_OWN,
    READ_ANY: PERMISSION_DOCUMENT_READ_ANY,
    UPDATE_OWN: PERMISSION_DOCUMENT_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_DOCUMENT_UPDATE_ANY,
    DELETE_OWN: PERMISSION_DOCUMENT_DELETE_OWN,
    DELETE_ANY: PERMISSION_DOCUMENT_DELETE_ANY,
  },
  KYCDOCUMENT: {
    CREATE_OWN: PERMISSION_KYCDOCUMENT_CREATE_OWN,
    CREATE_ANY: PERMISSION_KYCDOCUMENT_CREATE_ANY,
    READ_OWN: PERMISSION_KYCDOCUMENT_READ_OWN,
    READ_ANY: PERMISSION_KYCDOCUMENT_READ_ANY,
    UPDATE_OWN: PERMISSION_KYCDOCUMENT_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_KYCDOCUMENT_UPDATE_ANY,
    DELETE_OWN: PERMISSION_KYCDOCUMENT_DELETE_OWN,
    DELETE_ANY: PERMISSION_KYCDOCUMENT_DELETE_ANY,
  },
  ROLE: {
    CREATE_OWN: PERMISSION_ROLE_CREATE_OWN,
    CREATE_ANY: PERMISSION_ROLE_CREATE_ANY,
    READ_OWN: PERMISSION_ROLE_READ_OWN,
    READ_ANY: PERMISSION_ROLE_READ_ANY,
    UPDATE_OWN: PERMISSION_ROLE_UPDATE_OWN,
    UPDATE_ANY: PERMISSION_ROLE_UPDATE_ANY,
    DELETE_OWN: PERMISSION_ROLE_DELETE_OWN,
    DELETE_ANY: PERMISSION_ROLE_DELETE_ANY,
  },
};

// Example: Route to permission mapping (update as needed for your app)
export const ROUTE_PERMISSIONS = {
  "/dealer/:dealerId/mbo-management": [PERMISSIONS.DEALERSHIP.READ_OWN],
  "/dealer/:dealerId/mbo-management/:mboId": [PERMISSIONS.DEALERSHIP.READ_OWN],
  // Add more route-permission mappings as needed
};
